# obs: para executar um arquivo que não esteja no padrão docker-compose.yml deve-se utilizar o comando:
# docker-compose -f docker-compose-prod.yml up -d

version: "3"
services:
  api:
    image: nomedousuario/fastapi-app  # aqui é quando utilizamos docker hub
    ports:
      - 80:8000

    # aqui utilizamos as variáveis de ambiente do sistema operacional. o $ no caso é quando utilizamos linux  
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

 